## Liste de locaux et communes
Données tirées du [site de l'Etat de Genève](https://www.ge.ch/votations/20180304/federal/)

In [25]:
# import libraries
import pandas as pd
# import files
df_raw = pd.read_csv('./DATA_format_JSON/listeLocaux.csv', delimiter=';')
df_raw.head()

,commune_no,local_no,local-commune_nom,electorat,cartes-de-vote,bulletins,nuls,q1_blancs,q1_blancs_pc,q1_valables,...,q1_non_pc,q1_participation,q2_blancs,q2_blancs_pc,q2_valables,q2_oui,q2_oui_pc,q2_non,q2_non_pc,q2_participation
0,1,1,Aire-la-Ville,718,491,491,0,25,5.09%,466,...,14.59%,68.38%,6,1.22%,485,106,21.86%,379,78.14%,68.38%
1,2,1,Anières,1'313,869,869,0,20,2.30%,849,...,7.77%,66.18%,8,0.92%,861,178,20.67%,683,79.33%,66.18%
2,3,1,Avully,1'100,628,626,0,47,7.51%,579,...,15.72%,57.09%,8,1.28%,618,129,20.87%,489,79.13%,57.09%
3,4,1,Avusy,1'000,632,632,0,19,3.01%,613,...,9.46%,63.20%,1,0.16%,631,119,18.86%,512,81.14%,63.20%
4,5,1,Bardonnex,1'371,896,896,0,40,4.46%,856,...,14.49%,65.35%,7,0.78%,889,201,22.61%,688,77.39%,65.35%

In [26]:
# create new df and drop unnecessary columns
df_edt = df_raw.drop(['electorat', 'cartes-de-vote', 'bulletins','nuls','q1_blancs','q1_blancs_pc'
                      ,'q1_valables','q1_oui','q1_oui_pc','q1_non','q1_non_pc','q1_participation'
                      ,'q2_blancs','q2_blancs_pc','q2_valables','q2_oui','q2_oui_pc','q2_non','q2_non_pc'
                      ,'q2_participation'], axis=1)
df_edt.reset_index(drop=True, inplace=True)
df_edt.head(30)

    commune_no  local_no       local-commune_nom
0            1         1           Aire-la-Ville
1            2         1                 Anières
2            3         1                  Avully
3            4         1                   Avusy
4            5         1               Bardonnex
5            6         1                Bellevue
6            7         1                  Bernex
7            8         1                 Carouge
8            9         1                Cartigny
9           10         1                 Céligny
10          11         1                  Chancy
11          12         1  Chêne-Bougeries-Centre
12          12         2                 Conches
13          13         1             Chêne-Bourg
14          14         1                 Choulex
15          15         1            Collex-Bossy
16          16         1      Collonge-Bellerive
17          17         1                 Cologny
18          18         1               Confignon
19          19         1                 Corsier
20          20         1                Dardagny
21          21         1             Cité - Rive
22          21         2                  Pâquis
23          21         3           Saint-Gervais
24          21         4         Prairie-Délices
25          21         5        Eaux-Vives - Lac
26          21         6  Eaux-Vives - Frontenex
27          21         7   Florissant - Malagnou
28          21         8        Cluse - Roseraie
29          21         9                 Acacias

In [27]:
# remove accents and spec chars from local-commune_nom
# remove accents from local-commune_nom
df_edt['local-commune_nom'] = df_edt['local-commune_nom'].str.lower()
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='à',value='a')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='â',value='a')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='ä',value='a')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='é',value='e')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='è',value='e')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='ê',value='e')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='ï',value='i')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='ö',value='o')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='ô',value='o')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='ù',value='u')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace='ü',value='u')
# remove spec chars from local-commune_nom
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace=" - ",value=' ')
df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace="-",value=' ')
#df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace="'",value='_')
#df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace="   ",value=' ')
#df_edt['local-commune_nom'].replace(regex=True,inplace=True,to_replace=" ",value='_')
df_edt.head()

   commune_no  local_no local-commune_nom
0           1         1     aire la ville
1           2         1           anieres
2           3         1            avully
3           4         1             avusy
4           5         1         bardonnex

In [28]:
# create padded columns
df_edt['commune_no_padded'] = df_edt['commune_no'].astype(str).str.zfill(2)
df_edt['local_no_padded'] = df_edt['local_no'].astype(str).str.zfill(2)
# drop commune_no and local_no
df_edt.drop(['commune_no', 'local_no'], axis=1, inplace=True)
df_edt.head(30)

         local-commune_nom commune_no_padded local_no_padded
0            aire la ville                01              01
1                  anieres                02              01
2                   avully                03              01
3                    avusy                04              01
4                bardonnex                05              01
5                 bellevue                06              01
6                   bernex                07              01
7                  carouge                08              01
8                 cartigny                09              01
9                  celigny                10              01
10                  chancy                11              01
11  chene bougeries centre                12              01
12                 conches                12              02
13             chene bourg                13              01
14                 choulex                14              01
15            collex bossy                15              01
16      collonge bellerive                16              01
17                 cologny                17              01
18               confignon                18              01
19                 corsier                19              01
20                dardagny                20              01
21               cite rive                21              01
22                  paquis                21              02
23           saint gervais                21              03
24         prairie delices                21              04
25          eaux vives lac                21              05
26    eaux vives frontenex                21              06
27     florissant malagnou                21              07
28          cluse roseraie                21              08
29                 acacias                21              09

In [29]:
type(df_edt['commune_no_padded'])

pandas.core.series.Series

In [ ]:
# concatenate padded columns and drop them
df_edt['commLocal'] = df_edt['commune_no_padded'] + df_edt['local_no_padded']
# drop commune_no_padded and local_no_padded
df_edt.drop(['commune_no_padded', 'local_no_padded'], axis=1, inplace=True)
df_edt.head(30)

In [25]:
# export to csv
#df_local.to_csv('./electionBot_sBox/locals-Entities.csv',index=False)